config/routes.rb
Rails.application.routes.draw do
  root to: 'vehicles#index'
  resources :vehicles, only: [:index, :create] do
    get 'search', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id                  :bigint(8)        not null, primary key
#  vin                 :string
#  make                :string
#  model               :string
#  year                :integer
#  vehicle_type_name   :string
#  color               :string
#  current_meter_value :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end

  def search
    @vehicles = VehicleApiQuery.new(params).search
    respond_to do |format|
      format.js
    end
  end

  def create
    @vehicle = Vehicle.create(vehicle_params)
    respond_to do |format|
      format.js
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:vin, :make, :model, :year, :vehicle_type_name, :color, :current_meter_value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper

  def image(vehicle)
    image_tag((vehicle || 'default-car.jpg'), style: 'width: 100%;' )
  end
end

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %title Fleexpose
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/partials/_vehicle_list.html.haml
#vehicles-list
  .text-center= "#{pluralize(@vehicles.count, 'vehicle')} found"
  .row.justify-content-center
    - @vehicles.each do |v|
      .col-l-4.col-sm-6.col-xs-12
        .card.m-4.bg-dark
          .card-img-top
            = image(v['default_image_url_large'])
          .card-body
            %h5.card-title.text-center= v['name']
            .card-text
              %span VIN:
              = v['vin']
            .card-text{ data: { toggle: 'tooltip', placement: 'left'}, title: "Last Updated: #{v['updated_at']}" }
              %span ODO:
              = number_with_delimiter v['current_meter_value'].to_i
              mi
            .card-text
              %span Year
              = v['year']
          .card-footer
            = button_to 'Save', vehicles_path(vehicle: v), remote: true, class: 'btn btn-block btn-success', data: { disable_with: 'Saving!' }

app/views/partials/_vehicles_table.html.haml
%table.table.table-bordered.table-striped#vehicles-table
  %thead
    %tr
      Current Fleet
    %tr
      %th Make
      %th Model
      %th Year
      %th VIN
      %th Color
  %tbody#vehicles-table-body
    = render @vehicles

app/views/vehicles/_vehicle.html.haml
%tr
  %td= vehicle.make
  %td= vehicle.model
  %td= vehicle.year
  %td= vehicle.vin
  %td= vehicle.color

app/views/vehicles/_vehicle_list.html.haml
.text-center= "#{pluralize(@vehicles.count, 'vehicle')} were found"
%br
.container
  .row.justify-content-center
    - @vehicles.each do |v|
      .col-md-4
        .card.m-4
          .card-img-top.img-fluid
            = image(v)
          .card-body
            %h5.card-title= v['name']
            .card-text
              %span.text-muted VIN:
              = v['vin']
            .card-text{ data: { toggle: 'tooltip', placement: 'left'}, title: "Last Updated: #{v['updated_at']}" }
              %span.text-muted ODO:
              = number_with_delimiter v['current_meter_value']
              mi
            .card-text
              %span.text-muted Year
              = v['year']
          .card-footer
            = button_to 'Save', vehicles_path(vehicle: v), method: :post, class: 'btn btn-block btn-success', data: { disable_with: 'Saving!' }
            -# = link_to 'Save', vehicles_path(vehicle: v), method: :post, class: 'btn btn-block btn-success'

app/views/vehicles/create.js.erb
$('#vehicles-list').fadeOut();
$('#vehicles-table').append('<%= j render(@vehicle)%>');

app/views/vehicles/index.html.haml
.container-fluid
  %h1.text-center FLEETIO VIN TOOL
  = form_tag search_vehicles_path, method: :get, remote: true, id: 'search-form', class: 'form-inline justify-content-center mb-2' do
    .form-group
      = text_field_tag :vin, '', placeholder: 'Enter part of VIN', class: 'form-control input-lg mr-sm-2'
      = submit_tag "Search", class: 'btn btn-primary', data: { disable_with: 'Finding Matches'}
  = render partial: 'partials/vehicles_table'
#vehicles-search

app/views/vehicles/search.js.erb
$('#vehicles-search').html(" <%= j(render(partial: 'partials/vehicle_list')) %>");